# Generated by Django 3.0 on 2023-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.BigIntegerField(unique=True)),
                ('book_title', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=255)),
                ('author_origin', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('date_received', models.DateField()),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
    ]
